// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqfddgoutqsmuzruwwik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxZmRkZ291dHFzbXV6cnV3d2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTQ5ODEsImV4cCI6MjA2Nzc5MDk4MX0.JODnxjo-CbS0Pz9hhGiqDTrUpQvqfifnZnOg8ZVCy5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});